/// Flutter icons IconDark5Gray
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconDark5Gray
///      fonts:
///       - asset: fonts/IconDark5Gray.ttf
///
/// 
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
///
import 'package:flutter/widgets.dart';

class IconDark5Gray {
  IconDark5Gray._();

  static const _kFontFam = 'IconDark5Gray';
  static const String? _kFontPkg = null;

  static const IconData help_circled = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_add = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
