/// Flutter icons IconDark1Black
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconDark1Black
///      fonts:
///       - asset: fonts/IconDark1Black.ttf
///
/// 
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
///
import 'package:flutter/widgets.dart';

class IconDark1Black {
  IconDark1Black._();

  static const _kFontFam = 'IconDark1Black';
  static const String? _kFontPkg = null;

  static const IconData help_circled = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_add = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
